name:                meerkat
version:             0.4.0.0
github:              "mpowered/meerkat"
license:             BSD3
author:              "Shaun Sharples"
maintainer:          "shaun.sharples@gmail.com"
copyright:           "2020 Shaun Sharples"
description:         Please see the README on GitHub at <https://github.com/mpowered/meerkat#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >= 1.4 && < 1.5
- aeson-extra >= 0.4 && < 0.5
- async >= 2.2 && < 2.3
- base >= 4.7 && < 5
- beam-core >= 0.8 && < 0.9
- beam-postgres >= 0.4 && < 0.5
- bytestring >= 0.10 && < 0.11
- directory >= 1.3 && < 1.4
- errors >= 2.3 && < 2.4
- filepath >= 1.4 && < 1.5
- hedis >= 0.12.13 && < 0.13
- hostname >= 1.0 && < 1.1
- logging >= 3.0 && < 3.1
- megaparsec >= 7.0 && < 7.1
- modern-uri >= 0.3 && < 0.4
- optparse-applicative  >= 0.15 && < 0.16
- pqueue >= 1.4 && < 1.5
- resource-pool >= 0.2 && < 0.3
- recursion-schemes >= 5.1 && < 5.2
- req >= 3.3 && < 3.5
- scientific >= 0.3 && < 0.4
- stm >= 2.5 && < 2.6
- text >= 1.2 && < 1.3
- time >= 1.8 && < 1.9
- typed-process >= 0.2 && < 0.3
- unordered-containers >= 0.2 && < 0.3
- vector >= 0.12 && < 0.13
- yaml >= 0.11 && < 0.12
- xeno >= 0.4 && < 0.5

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src

executable:
  main:                Main.hs
  source-dirs:         app
  ghc-options:
  - -threaded
  - -rtsopts
  - "-with-rtsopts=-N -I0"
  dependencies:
  - meerkat

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - meerkat
