name:                meerkat
version:             0.5.1
github:              "mpowered/meerkat"
license:             BSD3
author:              "Shaun Sharples"
maintainer:          "shaun.sharples@gmail.com"
copyright:           "2020 Shaun Sharples"
description:         Please see the README on GitHub at <https://github.com/mpowered/meerkat#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- aeson >= 1.5 && < 1.6
- aeson-extra >= 0.4 && < 0.6
- async >= 2.2 && < 2.3
- base >= 4.7 && < 5
- beam-core >= 0.9 && < 0.10
- beam-postgres >= 0.5 && < 0.6
- bytestring >= 0.10 && < 0.11
- directory >= 1.3 && < 1.4
- errors >= 2.3 && < 2.4
- filepath >= 1.4 && < 1.5
- hedis >= 0.13 && < 0.15
- hostname >= 1.0 && < 1.1
- logging >= 3.0 && < 3.1
- megaparsec >= 9.0 && < 9.1
- modern-uri >= 0.3 && < 0.4
- optparse-applicative  >= 0.15 && < 0.17
- pqueue >= 1.4 && < 1.5
- resource-pool >= 0.2 && < 0.3
- recursion-schemes >= 5.2 && < 5.3
- req >= 3.8 && < 3.10
- scientific >= 0.3 && < 0.4
- stm >= 2.5 && < 2.6
- text >= 1.2 && < 1.3
- time >= 1.9 && < 1.10
- typed-process >= 0.2 && < 0.3
- unordered-containers >= 0.2 && < 0.3
- vector >= 0.12 && < 0.13
- yaml >= 0.11 && < 0.12
- xeno >= 0.4 && < 0.5

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src

executables:
  meerkat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -Iw60 --disable-delayed-os-memory-return"'
    dependencies:
    - meerkat

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - meerkat
