name:                meerkat
version:             0.2.3.0
github:              "mpowered/meerkat"
license:             BSD3
author:              "Shaun Sharples"
maintainer:          "shaun.sharples@gmail.com"
copyright:           "2019 Shaun Sharples"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mpowered/meerkat#readme>

dependencies:
- aeson >= 1.4 && < 1.5
- async >= 2.2 && < 2.3
- base >= 4.7 && < 5
- beam-core >= 0.8 && < 0.9
- beam-postgres >= 0.4 && < 0.5
- bytestring >= 0.10 && < 0.11
- errors >= 2.3 && < 2.4
- hedis >= 0.12 && < 0.13
- hostname >= 1.0 && < 1.1
- logging >= 3.0 && < 3.1
- megaparsec >= 7.0 && < 7.1
- optparse-applicative  >= 0.14 && < 0.15
- pqueue >= 1.4 && < 1.5
- resource-pool >= 0.2 && < 0.3
- req >= 2.1 && < 2.2
- scientific >= 0.3 && < 0.4
- stm >= 2.5 && < 2.6
- text >= 1.2 && < 1.3
- time >= 1.8 && < 1.9
- typed-process >= 0.2 && < 0.3
- unordered-containers >= 0.2 && < 0.3
- yaml >= 0.11 && < 0.12

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src

executables:
  meerkat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - "-with-rtsopts=-N -I0"
    dependencies:
    - meerkat

tests:
  meerkat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - meerkat
